### PR TITLE
[translation] Localize app + add translations #3

### PR DESCRIPTION
**Pull request by jasonsrogers**
## Issue
https://github.com/JiggyDevs/twikkl-app/issues/3

In this PR, we introduce `react-i18next` to manage loading, displaying and switch between different localisation.

Focus of the PR is around the technical changes to add localisation, actual translations should be done as followup tasks on a per language basis.

Initial languages files created: 
- ar: Arabic
- ch: Chines
- en: English (default)
- fr: French
- hi: Hindi

For convenience, a simple language switch was added to the Profile page

Screenshot 2023-05-28 at 21 19 29

### CODE REVIEW

**Comment by Vcky4** [comment]
I have observed that the translation files do not contain translations for each of the languages, is that intentional?

**Comment by jasonsrogers** [comment]
> I have observed that the translation files do not contain translations for each of the languages, is that intentional?

Hi @Vcky4

As I mentioned in the PR description `actual translations should be done as followup tasks on a per language basis`.

This is to keep the PR small but also to ensure translations are done properly as not a lot of people can translate 5 languages.

If you want I can google translate the entries for this PR, but as a general principle I would recommend splitting adding new keys and translating to different languages as different tasks

**Comment by jasonsrogers** [comment]
Language files are now translated (using google translate) and language selection is persisted locally by using `i18next-browser-languagedetector`

**Comment by Vcky4** [comment]
that's great

I'll merge this one

**Pull request merged**
